### ISSUE TITLE
Potential issue in linear_residuals function?

### ISSUE THREAD

**Issue by nicogarciaara** [David-Woroniuk/chowtest#1]
Hi! I was using the library with a dummy dataframe and when trying to use the chowtest function, I was getting the following error message: "TypeError: 'float' object is not subscriptable" when getting to line 47 in the linear_residuals function. I changed the existing line for the following one and the problem disappeared:

``yhat_list = [float(x) for x in model.predict(X)]``

Just raising this issue in case it helps :) 
Have a nice week!

**Comment by David-Woroniuk** [comment]
Hi!

Thanks for the feedback. Is it possible for you to send/post some sample code? It seems to work for a few test cases:

from chow_test import chowtest
chowtest(df[['a']], df[['b']], 9,10, 0.05)

My guess is that the handling of the Pandas DataFrame column (denoted by [['a']] and [['b']]) is different to the handling of a Pandas Series (['a'] or ['b'])

**Comment by nicogarciaara** [comment]
Hi! Yes, sure! I send here the code I was using:

`import pandas as pd
from chow_test import chowtest

df = pd.read_csv("example.csv")
df_test = df[df['week'] == 19]
df_train = df[df['week'] < 19]

df_train['break'] = 0

regressors = ['lag_1', 'lag_2', 'lag_3', 'lag_4', 'diff_1', 'diff_2']

weeks = list(df_train['week'].unique())
weeks.sort()

skus = df_train['prod'].unique()

for sku in skus:
    df_sku = df_train[df_train['prod'] == sku].reset_index(drop=True)
    df_sku = df_sku.sort_values(by=['week'])
    for i in range(2, len(weeks) - 2):
        chow_result = chowtest(df_sku[regressors], 
                               df_sku['demand'], i, i+1, 0.05)
        if chow_result[1] <= 0.05:
        	df_train.loc[(df_train['prod'] == sku) & (df_train['week'] >= weeks[i]), 'break'] = 1
        	df_test.loc[df_test['prod'] == sku, 'break'] = 1`

As I mentioned, I had to modify the linear_residuals function to make this work.
Thanks!

**Comment by David-Woroniuk** [comment]
Hi!

As mentioned above, I believe the issue to arise from handling Pandas Series' vs DataFrame.

[regressors] will return pandas.Series whereas [[regressors]] will return a one column pandas.DataFrame and
['demand'] will return pandas.Series whereas [['demand']] will return a one column pandas.DataFrame. 

https://stackoverflow.com/questions/33813223/whats-the-difference-between-and-in-pandas

Let me know if this solves the issue!

**Comment by nicogarciaara** [comment]
Yes, great. This has solved the issue. Thanks!
